#!/bin/bash
_tunet-bash_completions() {
    local cur prev opts auth_opts
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD - 1]}"
    opts="-c --config -i --login -o --logout -w --whoami -v --verbose --pass -a --auth --date-format --version"
    auth_opts="4 6 auto"
    case "$prev" in
    -a | --auth)
        COMPREPLY=($(compgen -W "${auth_opts}" -- "${cur}"))
        return 0
        ;;
    --date-format)
        COMPREPLY=($(compgen -W "Format String passed to date command" -- "${cur}"))
        return 0
        ;;
    esac
    if [[ ${cur} == -* ]]; then
        COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
        return 0
    fi
} && complete -F _tunet-bash_completions tunet-bash
